/**
 * Datos de ejemplo para inicializar la app si localStorage está vacío.
 * Incluye diversidad de tipos, precios, condiciones y marcas.
 */

const IMG_BASE = 'https://placehold.co/800x600/1a1a24/f59e0b?text='

export const seedCars = [
  {
    id: '1',
    marca: 'Toyota',
    modelo: 'RAV4',
    version: 'Sport 4x4',
    año: 2023,
    condicion: 'Seminuevo',
    estado: 'Activo',
    destacado: true,
    precio: 580000,
    precioAnterior: 620000,
    negociable: true,
    enganche: 116000,
    mensualidades: 8500,
    kilometraje: 12000,
    transmision: 'Automática',
    combustible: 'Gasolina',
    motor: '2.5L 4 cil.',
    cilindros: 4,
    hp: 203,
    traccion: 'AWD',
    colorExterior: '#1a1a2e',
    colorInterior: 'Beige',
    puertas: 5,
    pasajeros: 5,
    vin: '4T3BWRFV0PU012345',
    placas: 'AAA-12-34',
    tipo: 'SUV',
    descripcion: 'RAV4 Sport en excelente condición, único dueño. Servicio al corriente en agencia Toyota. Llantas nuevas, pintura original sin rayones. Historial de mantenimiento completo.',
    historialServicio: 'Mantenimientos en agencia Toyota cada 5,000 km. Último servicio: noviembre 2024.',
    dueñosPrevios: 1,
    equipamiento: ['Bolsas de aire', 'ABS', 'Control de estabilidad', 'Cámara trasera', 'Sensores de estacionamiento', 'A/C dual', 'Asientos de cuero', 'Pantalla táctil', 'Apple CarPlay', 'Android Auto', 'Rines de aleación', 'Faros LED'],
    imagenes: [`${IMG_BASE}RAV4+Sport`, `${IMG_BASE}RAV4+Interior`, `${IMG_BASE}RAV4+Motor`],
    fechaAgregado: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    marca: 'Honda',
    modelo: 'Civic',
    version: 'EX Turbo',
    año: 2022,
    condicion: 'Usado',
    estado: 'Activo',
    destacado: false,
    precio: 340000,
    precioAnterior: null,
    negociable: false,
    enganche: 68000,
    mensualidades: 4900,
    kilometraje: 35000,
    transmision: 'Manual',
    combustible: 'Gasolina',
    motor: '1.5L Turbo',
    cilindros: 4,
    hp: 174,
    traccion: 'FWD',
    colorExterior: '#c0c0c0',
    colorInterior: 'Negro',
    puertas: 4,
    pasajeros: 5,
    vin: '2HGFC2F81NH123456',
    placas: 'BBB-34-56',
    tipo: 'Sedán',
    descripcion: 'Civic EX en muy buenas condiciones, motor de alto rendimiento. Comprado de agencia, con toda la documentación en regla.',
    historialServicio: 'Servicio en Grupo Honda. Aceite y filtros al corriente.',
    dueñosPrevios: 1,
    equipamiento: ['Bolsas de aire', 'ABS', 'Cámara trasera', 'A/C', 'Pantalla táctil', 'Apple CarPlay', 'Android Auto', 'Bluetooth', 'Rines de aleación', 'Faros LED'],
    imagenes: [`${IMG_BASE}Civic+EX`, `${IMG_BASE}Civic+Interior`],
    fechaAgregado: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    marca: 'Ford',
    modelo: 'F-150',
    version: 'Lariat 4x4',
    año: 2024,
    condicion: 'Nuevo',
    estado: 'Activo',
    destacado: true,
    precio: 980000,
    precioAnterior: null,
    negociable: false,
    enganche: 196000,
    mensualidades: 14500,
    kilometraje: 500,
    transmision: 'Automática',
    combustible: 'Gasolina',
    motor: '3.5L V6 EcoBoost',
    cilindros: 6,
    hp: 400,
    traccion: '4x4',
    colorExterior: '#2c3e50',
    colorInterior: 'Cuero café',
    puertas: 4,
    pasajeros: 6,
    vin: '1FTFW1E80PFA00001',
    placas: null,
    tipo: 'Pickup',
    descripcion: 'F-150 Lariat nueva, sin uso. Motor EcoBoost de alta potencia con torque brutal. Equipada de fábrica con todas las amenidades de lujo.',
    historialServicio: 'Vehículo nuevo, garantía de fábrica vigente.',
    dueñosPrevios: 0,
    equipamiento: ['Bolsas de aire', 'ABS', 'Control de estabilidad', 'Cámara trasera', 'Sensores de estacionamiento', 'Alerta de colisión', 'A/C dual', 'Asientos de cuero', 'Asientos eléctricos', 'Calefacción de asientos', 'Techo solar', 'Pantalla táctil', 'Apple CarPlay', 'Android Auto', 'GPS integrado', 'Bluetooth', 'Carga inalámbrica', 'Sonido premium', 'Rines de aleación', 'Barras de techo', 'Faros LED', 'Faros adaptativos'],
    imagenes: [`${IMG_BASE}F-150+Lariat`, `${IMG_BASE}F-150+Interior`, `${IMG_BASE}F-150+Motor`, `${IMG_BASE}F-150+Cajuela`],
    fechaAgregado: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    marca: 'Volkswagen',
    modelo: 'Tiguan',
    version: 'Comfortline Plus',
    año: 2022,
    condicion: 'Seminuevo',
    estado: 'Activo',
    destacado: true,
    precio: 450000,
    precioAnterior: 490000,
    negociable: true,
    enganche: 90000,
    mensualidades: 6500,
    kilometraje: 28000,
    transmision: 'Automática',
    combustible: 'Gasolina',
    motor: '1.4L TSI',
    cilindros: 4,
    hp: 150,
    traccion: 'FWD',
    colorExterior: '#ffffff',
    colorInterior: 'Gris',
    puertas: 5,
    pasajeros: 5,
    vin: 'WVGZZZ5NZPW000001',
    placas: 'CCC-56-78',
    tipo: 'SUV',
    descripcion: 'Tiguan Comfortline Plus impecable. Doble dueño, siempre en agencia para sus servicios. Factura original, sin reporte.',
    historialServicio: 'Mantenimientos cada 10,000 km en agencia VW Pedregal.',
    dueñosPrevios: 2,
    equipamiento: ['Bolsas de aire', 'ABS', 'Control de estabilidad', 'Cámara trasera', 'Sensores de estacionamiento', 'A/C', 'Asientos de cuero', 'Pantalla táctil', 'Apple CarPlay', 'Android Auto', 'Bluetooth', 'Rines de aleación', 'Faros LED'],
    imagenes: [`${IMG_BASE}Tiguan+VW`, `${IMG_BASE}Tiguan+Interior`],
    fechaAgregado: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    marca: 'Chevrolet',
    modelo: 'Equinox',
    version: 'Premier AWD',
    año: 2021,
    condicion: 'Usado',
    estado: 'Activo',
    destacado: false,
    precio: 390000,
    precioAnterior: 420000,
    negociable: true,
    enganche: 78000,
    mensualidades: 5700,
    kilometraje: 52000,
    transmision: 'Automática',
    combustible: 'Gasolina',
    motor: '1.5L Turbo',
    cilindros: 4,
    hp: 170,
    traccion: 'AWD',
    colorExterior: '#8b0000',
    colorInterior: 'Negro',
    puertas: 5,
    pasajeros: 5,
    vin: '3GNAXUEG5ML000001',
    placas: 'DDD-78-90',
    tipo: 'SUV',
    descripcion: 'Equinox Premier bien cuidado. Motor turbo eficiente, tracción integral. Ideal para familia.',
    historialServicio: 'Servicios en distribuidora Chevrolet. Aceite sintético siempre.',
    dueñosPrevios: 1,
    equipamiento: ['Bolsas de aire', 'ABS', 'Control de estabilidad', 'Cámara trasera', 'Sensores de estacionamiento', 'A/C dual', 'Asientos de cuero', 'Asientos eléctricos', 'Pantalla táctil', 'Apple CarPlay', 'Android Auto', 'Bluetooth', 'Rines de aleación', 'Faros LED'],
    imagenes: [`${IMG_BASE}Equinox+Premier`, `${IMG_BASE}Equinox+Interior`],
    fechaAgregado: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '6',
    marca: 'Mazda',
    modelo: 'CX-5',
    version: 'Signature AWD',
    año: 2023,
    condicion: 'Seminuevo',
    estado: 'Activo',
    destacado: true,
    precio: 520000,
    precioAnterior: null,
    negociable: false,
    enganche: 104000,
    mensualidades: 7600,
    kilometraje: 8000,
    transmision: 'Automática',
    combustible: 'Gasolina',
    motor: '2.5L Turbo',
    cilindros: 4,
    hp: 256,
    traccion: 'AWD',
    colorExterior: '#8b4513',
    colorInterior: 'Terracota',
    puertas: 5,
    pasajeros: 5,
    vin: 'JM3KFADM2P0000001',
    placas: 'EEE-90-12',
    tipo: 'SUV',
    descripcion: 'CX-5 Signature, el top de la gama. Interiores de cuero Nappa, sonido Bose, techo panorámico. Prácticamente nueva.',
    historialServicio: 'Un servicio en agencia Mazda a los 5,000 km.',
    dueñosPrevios: 1,
    equipamiento: ['Bolsas de aire', 'ABS', 'Control de estabilidad', 'Cámara trasera', 'Sensores de estacionamiento', 'Alerta de colisión', 'A/C dual', 'Asientos de cuero', 'Asientos eléctricos', 'Calefacción de asientos', 'Techo panorámico', 'Pantalla táctil', 'Apple CarPlay', 'Android Auto', 'GPS integrado', 'Bluetooth', 'Carga inalámbrica', 'Sonido premium', 'Rines de aleación', 'Faros LED', 'Faros adaptativos'],
    imagenes: [`${IMG_BASE}CX5+Signature`, `${IMG_BASE}CX5+Interior`, `${IMG_BASE}CX5+Techo`],
    fechaAgregado: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '7',
    marca: 'Nissan',
    modelo: 'Sentra',
    version: 'Advance',
    año: 2021,
    condicion: 'Usado',
    estado: 'Activo',
    destacado: false,
    precio: 265000,
    precioAnterior: 285000,
    negociable: true,
    enganche: 53000,
    mensualidades: 3800,
    kilometraje: 45000,
    transmision: 'Automática',
    combustible: 'Gasolina',
    motor: '2.0L 4 cil.',
    cilindros: 4,
    hp: 145,
    traccion: 'FWD',
    colorExterior: '#4169e1',
    colorInterior: 'Negro',
    puertas: 4,
    pasajeros: 5,
    vin: '3N1AB8CV0MY000001',
    placas: 'FFF-12-34',
    tipo: 'Sedán',
    descripcion: 'Sentra Advance en buenas condiciones. Económico en combustible, ideal para ciudad. Sin detalles mecánicos.',
    historialServicio: 'Aceites y servicios regulares. Frenos revisados recientemente.',
    dueñosPrevios: 1,
    equipamiento: ['Bolsas de aire', 'ABS', 'Cámara trasera', 'A/C', 'Pantalla táctil', 'Apple CarPlay', 'Android Auto', 'Bluetooth', 'Rines de aleación'],
    imagenes: [`${IMG_BASE}Sentra+Advance`, `${IMG_BASE}Sentra+Interior`],
    fechaAgregado: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '8',
    marca: 'BMW',
    modelo: 'X3',
    version: 'xDrive30i M Sport',
    año: 2022,
    condicion: 'Seminuevo',
    estado: 'Activo',
    destacado: true,
    precio: 850000,
    precioAnterior: 920000,
    negociable: false,
    enganche: 170000,
    mensualidades: 12400,
    kilometraje: 22000,
    transmision: 'Automática',
    combustible: 'Gasolina',
    motor: '2.0L TwinPower Turbo',
    cilindros: 4,
    hp: 248,
    traccion: 'AWD',
    colorExterior: '#000000',
    colorInterior: 'Cuero negro',
    puertas: 5,
    pasajeros: 5,
    vin: 'WBA8A9C00P000001',
    placas: 'GGG-34-56',
    tipo: 'SUV',
    descripcion: 'X3 M Sport en condición premium. Paquete M Sport con parrilla frontal exclusiva, llantas 20" y suspensión deportiva. Un auto de verdadera presencia.',
    historialServicio: 'Mantenimientos BMW Performance Center. Garantía extendida activa.',
    dueñosPrevios: 1,
    equipamiento: ['Bolsas de aire', 'ABS', 'Control de estabilidad', 'Cámara trasera', 'Sensores de estacionamiento', 'Alerta de colisión', 'A/C dual', 'Asientos de cuero', 'Asientos eléctricos', 'Calefacción de asientos', 'Techo panorámico', 'Pantalla táctil', 'Apple CarPlay', 'Android Auto', 'GPS integrado', 'Bluetooth', 'Carga inalámbrica', 'Sonido premium', 'Rines de aleación', 'Faros LED', 'Faros adaptativos', 'Vidrios eléctricos'],
    imagenes: [`${IMG_BASE}BMW+X3+M`, `${IMG_BASE}BMW+X3+Interior`, `${IMG_BASE}BMW+X3+Motor`],
    fechaAgregado: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '9',
    marca: 'Kia',
    modelo: 'Sportage',
    version: 'GT Line',
    año: 2023,
    condicion: 'Nuevo',
    estado: 'Activo',
    destacado: false,
    precio: 495000,
    precioAnterior: null,
    negociable: false,
    enganche: 99000,
    mensualidades: 7200,
    kilometraje: 0,
    transmision: 'Automática',
    combustible: 'Híbrido',
    motor: '1.6L Turbo Híbrido',
    cilindros: 4,
    hp: 227,
    traccion: 'AWD',
    colorExterior: '#2e8b57',
    colorInterior: 'Negro/Verde',
    puertas: 5,
    pasajeros: 5,
    vin: 'KNDPNDAF8N0000001',
    placas: null,
    tipo: 'SUV',
    descripcion: 'Sportage GT Line híbrida, nueva en aparador. Diseño rompedor, ahorro de combustible superior. La SUV del futuro, hoy.',
    historialServicio: 'Vehículo nuevo con garantía de fábrica 5 años / 100,000 km.',
    dueñosPrevios: 0,
    equipamiento: ['Bolsas de aire', 'ABS', 'Control de estabilidad', 'Cámara trasera', 'Sensores de estacionamiento', 'Alerta de colisión', 'A/C dual', 'Asientos de cuero', 'Asientos eléctricos', 'Calefacción de asientos', 'Techo panorámico', 'Pantalla táctil', 'Apple CarPlay', 'Android Auto', 'GPS integrado', 'Bluetooth', 'Carga inalámbrica', 'Sonido premium', 'Rines de aleación', 'Faros LED'],
    imagenes: [`${IMG_BASE}Sportage+GT`, `${IMG_BASE}Sportage+Interior`],
    fechaAgregado: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '10',
    marca: 'Jeep',
    modelo: 'Wrangler',
    version: 'Rubicon 4xe',
    año: 2023,
    condicion: 'Seminuevo',
    estado: 'Activo',
    destacado: false,
    precio: 980000,
    precioAnterior: 1050000,
    negociable: true,
    enganche: 196000,
    mensualidades: 14300,
    kilometraje: 15000,
    transmision: 'Automática',
    combustible: 'Híbrido',
    motor: '2.0L Turbo 4xe',
    cilindros: 4,
    hp: 375,
    traccion: '4x4',
    colorExterior: '#ff4500',
    colorInterior: 'Negro',
    puertas: 4,
    pasajeros: 5,
    vin: '1C4HJXFN0PW000001',
    placas: 'HHH-78-90',
    tipo: 'SUV',
    descripcion: 'Wrangler Rubicon 4xe, el todoterreno más icónico ahora en versión híbrida enchufable. Capaz de todo, cero compromiso.',
    historialServicio: 'Un servicio de mantenimiento programado en agencia Jeep.',
    dueñosPrevios: 1,
    equipamiento: ['Bolsas de aire', 'ABS', 'Control de estabilidad', 'Cámara trasera', 'Sensores de estacionamiento', 'A/C', 'Pantalla táctil', 'Apple CarPlay', 'Android Auto', 'Bluetooth', 'Rines de aleación', 'Barras de techo', 'Faros LED'],
    imagenes: [`${IMG_BASE}Wrangler+Rubicon`, `${IMG_BASE}Wrangler+Interior`, `${IMG_BASE}Wrangler+Offroad`],
    fechaAgregado: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '11',
    marca: 'Mercedes-Benz',
    modelo: 'GLA 200',
    version: 'Sport',
    año: 2021,
    condicion: 'Usado',
    estado: 'Activo',
    destacado: false,
    precio: 620000,
    precioAnterior: 660000,
    negociable: false,
    enganche: 124000,
    mensualidades: 9000,
    kilometraje: 38000,
    transmision: 'Automática',
    combustible: 'Gasolina',
    motor: '1.3L Turbo',
    cilindros: 4,
    hp: 163,
    traccion: 'FWD',
    colorExterior: '#e8e8e8',
    colorInterior: 'Negro',
    puertas: 5,
    pasajeros: 5,
    vin: 'W1N4N4HB0MJ000001',
    placas: 'III-90-12',
    tipo: 'SUV',
    descripcion: 'GLA 200 Sport en impecable estado. Lujo alemán accesible. Sistema MBUX, sonido Burmester, líneas de diseño únicas.',
    historialServicio: 'Servicios en agencia Mercedes-Benz Santa Fe.',
    dueñosPrevios: 2,
    equipamiento: ['Bolsas de aire', 'ABS', 'Control de estabilidad', 'Cámara trasera', 'Sensores de estacionamiento', 'A/C dual', 'Asientos de cuero', 'Asientos eléctricos', 'Techo solar', 'Pantalla táctil', 'Bluetooth', 'Sonido premium', 'Rines de aleación', 'Faros LED'],
    imagenes: [`${IMG_BASE}GLA+200+Sport`, `${IMG_BASE}GLA+Interior`],
    fechaAgregado: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '12',
    marca: 'Audi',
    modelo: 'Q5',
    version: '40 TFSI Dynamic',
    año: 2022,
    condicion: 'Seminuevo',
    estado: 'Reservado',
    destacado: false,
    precio: 720000,
    precioAnterior: 780000,
    negociable: false,
    enganche: 144000,
    mensualidades: 10500,
    kilometraje: 20000,
    transmision: 'Automática',
    combustible: 'Gasolina',
    motor: '2.0L TFSI',
    cilindros: 4,
    hp: 204,
    traccion: 'AWD',
    colorExterior: '#4a4a4a',
    colorInterior: 'Cuero beige',
    puertas: 5,
    pasajeros: 5,
    vin: 'WA1BNAFY0N2000001',
    placas: 'JJJ-12-34',
    tipo: 'SUV',
    descripcion: 'Q5 Dynamic, el referente de las SUV premium medianas. Virtual Cockpit, sonido Bang & Olufsen, Matrix LED.',
    historialServicio: 'Servicios Audi Interlomas. Sin siniestros.',
    dueñosPrevios: 1,
    equipamiento: ['Bolsas de aire', 'ABS', 'Control de estabilidad', 'Cámara trasera', 'Sensores de estacionamiento', 'Alerta de colisión', 'A/C dual', 'Asientos de cuero', 'Asientos eléctricos', 'Calefacción de asientos', 'Techo panorámico', 'Pantalla táctil', 'Apple CarPlay', 'Android Auto', 'GPS integrado', 'Bluetooth', 'Carga inalámbrica', 'Sonido premium', 'Rines de aleación', 'Faros LED', 'Faros adaptativos'],
    imagenes: [`${IMG_BASE}Audi+Q5`, `${IMG_BASE}Audi+Q5+Interior`],
    fechaAgregado: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const seedLeads = [
  {
    id: 'l1',
    fecha: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    nombre: 'Carlos Mendoza',
    email: 'carlos.m@gmail.com',
    telefono: '5512345678',
    autoInteres: 'Toyota RAV4 Sport 4x4 2023',
    mensaje: 'Hola, me interesa el RAV4. ¿Aceptan financiamiento externo?',
    estado: 'Pendiente',
  },
  {
    id: 'l2',
    fecha: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    nombre: 'María Fernández',
    email: 'mfernandez@hotmail.com',
    telefono: '5598765432',
    autoInteres: 'BMW X3 xDrive30i M Sport 2022',
    mensaje: '¿Tienen el X3 en color azul? ¿Cuál es el precio de contado?',
    estado: 'Atendido',
  },
  {
    id: 'l3',
    fecha: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    nombre: 'Roberto Sánchez',
    email: 'r.sanchez@empresa.mx',
    telefono: '5567891234',
    autoInteres: 'Ford F-150 Lariat 4x4 2024',
    mensaje: 'Necesito la F-150 para trabajo. ¿Tienen disponibilidad inmediata? ¿Factura a nombre de empresa?',
    estado: 'Pendiente',
  },
]
